# Generated by Django 5.2.5 on 2025-08-07 17:50

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('monthly_salary', models.FloatField()),
                ('age', models.IntegerField()),
                ('approved_limit', models.FloatField()),
                ('current_debt', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('loan_amount', models.FloatField()),
                ('tenure', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('monthly_installment', models.IntegerField()),
                ('EMIs_paid_on_time', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('past', 'Past'), ('active', 'Active')], default='active', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='core.customer')),
            ],
        ),
    ]
